SirketCore/Models/Admin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SirketCore.Models
{
    public class Admin
    {
        [Key]
        public int AdminID { get; set; }

        [Column(TypeName ="Varchar(20)")]
        public string Kullanici { get; set; }

        [Column(TypeName = "Varchar(20)")]
        public string Sifre { get; set; }
    }
}

SirketCore/Models/Birim.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SirketCore.Models
{
    public class Birim
    {
        public int BirimID { get; set; }
        public string BirimAd { get; set; }

        public IList<Personel> Personels { get; set; }
    }
}

SirketCore/Models/Context.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SirketCore.Models
{
    public class Context :DbContext
    {
        public Context(DbContextOptions<Context> contextOptions) : base(contextOptions)
        {
        }
        public DbSet<Birim> Birims { get; set; }
        public DbSet<Personel> Personels { get; set; }
        public DbSet<Admin> Admins { get; set; }
    }
}

SirketCore/Models/ErrorViewModel.cs
using System;

namespace SirketCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SirketCore/Models/Personel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SirketCore.Models
{
    public class Personel
    {
        public int PersonelID { get; set; }
        public string Ad { get; set; }
        public String Soyad { get; set; }
        public string Sehir { get; set; }
        public int BirimID { get; set; }
        public Birim Birim { get; set; }
    }
}

SirketCore/Controllers/BirimController.cs
using Microsoft.AspNetCore.Mvc;
using SirketCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SirketCore.Controllers
{
    public class BirimController : Controller
    {
        private readonly Context _context;
        public BirimController(Context context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var listele = _context.Birims.ToList();
            return View(listele);
        }
        [HttpGet]
       public IActionResult YeniBirim()
        {
            return View();
        }

        [HttpPost]
        public IActionResult YeniBirim(Birim b)
        {
            _context.Birims.Add(b);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult BirimSil(int id)
        {
            var brmSil = _context.Birims.Find(id);
            _context.Birims.Remove(brmSil);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult BirimGetir(int id)
        {
            var brmGetir = _context.Birims.Find(id);
            return View("BirimGetir", brmGetir);
        }
        public IActionResult BirimGuncelle(Birim b)
        {
            var brmGuncelle = _context.Birims.Find(b.BirimID);
            brmGuncelle.BirimAd = b.BirimAd;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult BirimDetay(int id)
        {
            /*
            var list = (from birim in _context.Birims.ToList()
                        join deger in _context.Personels.ToList()
                        on birim.BirimID equals deger.BirimID

                        select new {
                            personelAd = deger.Ad,
                            personelSoyad =deger.Soyad,
                            personelSehir = deger.Sehir
                        }
                        ).ToList();
            */

            var degerler = _context.Personels.Where(x => x.BirimID == id).ToList();
            var brmad = _context.Birims.Where(x => x.BirimID == id).Select(y => y.BirimAd).FirstOrDefault();
            ViewBag.brm = brmad;
            return View(degerler);
        }
    }
}

SirketCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SirketCore.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SirketCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SirketCore/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using SirketCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SirketCore.Controllers
{
    public class LoginController : Controller
    {
        private readonly Context _context;
        public LoginController(Context context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult GirisYap()
        {
            return View();
        }

        public async Task<IActionResult> GirisYap(Admin p)
        {
           /* 
              Önce kullanıcı bilgisi kontrol edilir.
              Eğer kullanıcı varsa
              HttpContext.Session.SetInt32("session_adi", bilgiler.id); //Session kaydı

              ViewBag.UserId = HttpContext.Session.GetInt32("session_adi"); //Session get alma


              Her girişi zorunlu sayfada viewbag'in null olup olmadığını kontrol et
              Boşsa logine at
              Değilse view'i göster
           */
           //İLERİ SEVİYE IDENTITY SERVER 4 KONUSU BU
           //3 FARKLI YÖNTEM VAR ;
           /*
            1-) Claim Bazlı Doğrulama
            2-) Rol Bazlı Doğrulama
            3-) Cookie Bazlı Doğrulama
            */
            var bilgiler = _context.Admins.FirstOrDefault(x => x.Kullanici == p.Kullanici && x.Sifre == p.Sifre);
            if(bilgiler != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name,p.Kullanici)
                };
                var useridentity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(useridentity);
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index","Personelim");
            }
            return View();
        }

        public async Task<IActionResult> CikisYap()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("GirisYap");

        }
    }
}

SirketCore/Controllers/PersonelimController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SirketCore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SirketCore.Controllers
{
    public class PersonelimController : Controller
    {
        private readonly Context _context;
        public PersonelimController(Context context)
        {
            _context = context;
        } 
        [Authorize]
        public IActionResult Index()
        {
            var listele = _context.Personels.Include(x=>x.Birim).ToList();
            return View(listele);
        }

        [HttpGet]
        public IActionResult YeniPersonel()
        {
            //DropDownListFor Backend Kısmı
            ViewBag.yeniPersonel = _context.Birims.ToList();
            return View();
        }
        public IActionResult YeniPersonel(Personel p)
        {
            var personelEkle = _context.Birims.Where(x => x.BirimID == p.Birim.BirimID).FirstOrDefault();
            p.Birim = personelEkle;
            _context.Personels.Add(p);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SirketCore/Views/Birim/BirimDetay.cshtml
@using SirketCore.Models
@model List<Personel>

@{
    ViewData["Title"] = "BirimDetay";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

@*<small>Birim Detay Sayfası</small>*@

<h2 class="mt-2">@ViewBag.brm Detayları</h2>

<table class="table table-bordered mt-4">
    <tr class="bg-dark text-info">
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.PersonelID</td>
            <td>@k.Ad</td>
            <td>@k.Soyad</td>
            <td>@k.Sehir</td>
        </tr>
    }
</table>

SirketCore/Views/Birim/BirimGetir.cshtml
@model SirketCore.Models.Birim

@{
    ViewData["Title"] = "BirimGetir";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<small>Birim Güncelleme Sayfası</small>
@using (Html.BeginForm("BirimGuncelle", "Birim", FormMethod.Post))
{
    <b>Birim ID</b>
    @Html.TextBoxFor(x => x.BirimID, new { @class = "form-control ", @readonly = "readonly" })
    <br />
    <b>Birim Ad</b>
    @Html.TextBoxFor(x => x.BirimAd, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Birim Güncelle</button>
}

SirketCore/Views/Birim/BirimSil.cshtml
@{
    ViewData["Title"] = "BirimSil";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<h1>BirimSil</h1>

SirketCore/Views/Birim/Index.cshtml
@using SirketCore.Models
@model List<Birim>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<small>Birim Bilgisini Güncelleme Sayfası</small>
<table class="table table-bordered">
    <tr>
        <td>Birim ID</td>
        <td>Birim Adı</td>
        <td>Sil</td>
        <td>Güncelle</td>
        <td>Detay</td>
    </tr>
    @foreach(var k in Model)
            {
                <tr>
                    <td>@k.BirimID</td>
                    <td>@k.BirimAd</td>
                    <td><a href="/Birim/BirimSil/@k.BirimID" class="btn btn-danger">Sil</a></td>
                    <td><a href="/Birim/BirimGetir/@k.BirimID" class="btn btn-success">Güncelle</a></td>
                    <td><a href="/Birim/BirimDetay/@k.BirimID" class="btn btn-warning">Detay</a></td>
                </tr>
            }
</table>
<a href="/Birim/YeniBirim" class="btn btn-primary">Yeni Birim Ekle</a>

SirketCore/Views/Birim/YeniBirim.cshtml
@model SirketCore.Models.Birim
@{
    ViewData["Title"] = "YeniBirim";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<small>Yeni Birim Ekleme Sayfası</small>

<form class="form-group mt-5" method="post">
    <b>Eklenecek Birim Adını Giriniz</b>
    @Html.TextBoxFor(x => x.BirimAd, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Yeni Birim Ekle</button>
</form>

SirketCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SirketCore/Views/Login/GirisYap.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>MVC Core Giriş Formu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Blend  Login Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="~/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/web/css/font-awesome.css" rel="stylesheet"> <!-- Font-Awesome-Icons-CSS -->
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href="//fonts.googleapis.com/css?family=Vollkorn+SC:400,600,700,900&amp;subset=cyrillic,cyrillic-ext,latin-ext,vietnamese" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Acme" rel="stylesheet">
    <!-- //web font -->
</head>
<body>
    <!-- main -->
    <div class="main">
        <h1>MVC Core Giriş Formu</h1>
        <div class="main-w3lsrow">
            <!-- login form -->
            <div class="login-form login-form-left">
                <div class="agile-row">
                    <h2>Giriş Yap</h2>
                    <div class="login-agileits-top">
                        <form action="#" method="post">
                            <p>Kullanıcı Adı </p>
                            <input type="text" class="name" name="kullanici" required="" />
                            <p>Şifre</p>
                            <input type="password" class="password" name="sifre" required="" />
                            <label class="anim">
                                <input type="checkbox" class="checkbox">
                                <span> Beni Hatırla</span>
                            </label>
                            <input type="submit" value="Login">
                        </form>
                    </div>
                    <div class="login-agileits-bottom">
                        <h6><a href="#">Şifremi Unuttum</a></h6>
                    </div>
                    <div class="login-agileits-bottom1">
                        <h3>(ya da şunlarla giriş yap)</h3>

                    </div>
                    <div class="social_icons agileinfo">
                        <ul class="top-links">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
        <!-- copyright -->
        <div class="copyright">
            <p> © 2021 Tüm Hakları Saklıdır</p>
        </div>
        <!-- //copyright -->
    </div>
    <!-- //main -->
</body>
</html>

SirketCore/Views/Personelim/Index.cshtml
@using SirketCore.Models
@model List<Personel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<small>Personeller listesi</small>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Birim</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach(var k in Model)
            {
         <tr>
             <td>@k.PersonelID</td>
             <td>@k.Ad</td>
             <td>@k.Soyad</td>
             <td>@k.Sehir</td>
             <td>@k.Birim.BirimAd</td>
             <td><a href="/Personelim/PersonelSil" class="btn btn-danger">Sil</a></td>
             <td><a href="/Personelim/PersonelGetir" class="btn btn-success">Güncelle</a></td>
         </tr>
            }
</table>
<a href="/Personelim/YeniPersonel" class="btn btn-primary">Yeni Personel Ekle</a>

SirketCore/Views/Personelim/YeniPersonel.cshtml
@model SirketCore.Models.Personel

@{
    ViewData["Title"] = "YeniPersonel";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<small>Yeni Personel Ekleme Sayfası</small>

<form class="form-group" method="post">
    <b>Personel Adı</b>
    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    <br />
    <b>Personel Soyadı</b>
    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
    <br />
    <b>Personel Sehir</b>
    @Html.TextBoxFor(x => x.Sehir, new { @class = "form-control" })
    <br />
    @*//DropDownListFor Frontend Kısmı*@
    <b>Personel Birimi</b>
    @*@Html.DropDownListFor(x => x.Birim.BirimID, new SelectList(ViewBag.dgr, "BirimID", "BirimAd"), "Lütfen Birim Seçiniz", new { @class = "form-control" })*@
    @Html.DropDownListFor(x => x.Birim.BirimID, new SelectList(ViewBag.yeniPersonel, "BirimID", "BirimAd"), "Lütfen Birim Seçiniz", new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Personel Ekle</button>
</form>

SirketCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SirketCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SirketCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SirketCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SirketCore/Views/Shared/_TestLayout.cshtml
@{
    ViewData["Title"] = "_TestLayout";
}

<!DOCTYPE html>
<html>
<head>
    <title>Şirket Core</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menüler</h3>
        <a href="/Birim/Index" class="w3-bar-item w3-button">Birimler</a>
        <a href="/Personelim/Index" class="w3-bar-item w3-button">Personeller</a>
        <a href="#" class="w3-bar-item w3-button">Hakkımızda</a>
        <a href="@Url.Action("CikisYap","Login")" class="w3-bar-item w3-button">Çıkış</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-teal">
            <h1>Asp.Net Mvc ŞirketCore Projesi</h1>
        </div>

        <div class="w3-container">
        @RenderBody()
        </div>

    </div>

</body>
</html>